<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HUB.Media.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HUB.Media.Domain\HUB.Media.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HUB.Shared.Contracts\HUB.Shared.Contracts.csproj" />
  </ItemGroup>
</Project>
