<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HUB.Shared.Messaging</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HUB.Shared.Contracts\HUB.Shared.Contracts.csproj" />
  </ItemGroup>
</Project>
